features:
  allow_slashes_in_filenames: true

app_users:
  test-user: 'password'

user:
  locations:
    location1:
      - ip.address1
      - ip.address2
    location2:
      - ip.address1
      - ip.address3
      - ip.address4
